name: GitHub Actions Shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: check repository shell script
        uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
      - name: install write-good
        run: npm install -g write-good
      - name: use write-good
        run: write-good *.md
