name: GitHub Actions Shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: check repository shell script
        uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
      - name: Lint Markdown
        uses: tomwhross/write-good-action@v1.6
