name: GitHub Actions Shellcheck
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: check repository shell script
        uses: actions/checkout@v3
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
      - name: use write-good to checkout md files
        run: |
          npm install -g write-good
          write-good *.md
      - name: use proselint to checkout md files
        run: | 
          pip install proselint
          proselint *.md
      
